steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}",
        ".",
      ]

  # 2. Push the Docker image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}",
      ]

  # 3. Deploy the new image to Google Cloud Run, using secrets from Secret Manager
  # 3. Deploy the new image to Google Cloud Run, using secrets from Secret Manager
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "${_INSTANCE_CONNECTION_NAME}"
      - "--set-env-vars"
      - "NODE_ENV=production"
      - "--update-secrets=JWT_SECRET=JWT_SECRET:latest"

  # 4. Update the service with the DB_PASS secret
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "${_SERVICE_NAME}"
      - "--region"
      - "${_REGION}"
      - "--update-secrets=DB_PASS=DB_PASS:latest"

# Define the images to be pushed to Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"

# Define user-configurable substitutions
substitutions:
  _PROJECT_ID: "vitacross"
  _REGION: "us-west2"
  _SERVICE_NAME: "inbound-medical-app"
  _REPOSITORY: "inbound-medical-repo"
  _INSTANCE_CONNECTION_NAME: "vitacross:us-west2:vitacross-database"
  _DB_USER: "app_user"
  _DB_NAME: "inbound_medical"

# Set the timeout for the build
timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY

